<?xml version="1.0" encoding="UTF-8"?>
<ECF>
    <DescuentosORecargos>
        <DescuentoORecargo>
            <DescripcionDescuentooRecargo>STR</DescripcionDescuentooRecargo>
            <IndicadorFacturacionDescuentooRecargo>4</IndicadorFacturacionDescuentooRecargo>
            <IndicadorNorma1007>1</IndicadorNorma1007>
            <MontoDescuentooRecargo>STR</MontoDescuentooRecargo>
            <MontoDescuentooRecargoOtraMoneda>STR</MontoDescuentooRecargoOtraMoneda>
            <NumeroLinea>STR</NumeroLinea>
            <TipoAjuste>R</TipoAjuste>
            <TipoValor>%</TipoValor>
            <ValorDescuentooRecargo>STR</ValorDescuentooRecargo>
        </DescuentoORecargo>
    </DescuentosORecargos>
    <DetallesItems>
        <Item>
            <CantidadItem>STR</CantidadItem>
            <CantidadReferencia>STR</CantidadReferencia>
            <DescripcionItem>STR</DescripcionItem>
            <DescuentoMonto>STR</DescuentoMonto>
            <FechaElaboracion>STR</FechaElaboracion>
            <FechaVencimientoItem>STR</FechaVencimientoItem>
            <GradosAlcohol>STR</GradosAlcohol>
            <IndicadorBienoServicio>2</IndicadorBienoServicio>
            <IndicadorFacturacion>4</IndicadorFacturacion>
            <MontoItem>STR</MontoItem>
            <NombreItem>STR</NombreItem>
            <NumeroLinea>STR</NumeroLinea>
            <OtraMonedaDetalle>
                <DescuentoOtraMoneda>STR</DescuentoOtraMoneda>
                <MontoItemOtraMoneda>STR</MontoItemOtraMoneda>
                <PrecioOtraMoneda>STR</PrecioOtraMoneda>
                <RecargoOtraMoneda>STR</RecargoOtraMoneda>
            </OtraMonedaDetalle>
            <PrecioUnitarioItem>STR</PrecioUnitarioItem>
            <PrecioUnitarioReferencia>STR</PrecioUnitarioReferencia>
            <RecargoMonto>STR</RecargoMonto>
            <Retencion>
                <IndicadorAgenteRetencionoPercepcion>2</IndicadorAgenteRetencionoPercepcion>
                <MontoISRRetenido>STR</MontoISRRetenido>
                <MontoITBISRetenido>STR</MontoITBISRetenido>
            </Retencion>
            <TablaCodigosItem>
                <CodigosItem>
                    <CodigoItem>STR</CodigoItem>
                    <TipoCodigo>STR</TipoCodigo>
                </CodigosItem>
            </TablaCodigosItem>
            <TablaImpuestoAdicional>
                <ImpuestoAdicional>
                    <TipoImpuesto>039</TipoImpuesto>
                </ImpuestoAdicional>
            </TablaImpuestoAdicional>
            <TablaSubDescuento>
                <SubDescuento>
                    <MontoSubDescuento>STR</MontoSubDescuento>
                    <SubDescuentoPorcentaje>STR</SubDescuentoPorcentaje>
                    <TipoSubDescuento>%</TipoSubDescuento>
                </SubDescuento>
            </TablaSubDescuento>
            <TablaSubRecargo>
                <SubRecargo>
                    <MontoSubRecargo>STR</MontoSubRecargo>
                    <SubRecargoPorcentaje>STR</SubRecargoPorcentaje>
                    <TipoSubRecargo>%</TipoSubRecargo>
                </SubRecargo>
            </TablaSubRecargo>
            <TablaSubcantidad>
                <SubcantidadItem>
                    <CodigoSubcantidad>62</CodigoSubcantidad>
                    <Subcantidad>STR</Subcantidad>
                </SubcantidadItem>
            </TablaSubcantidad>
            <UnidadMedida>62</UnidadMedida>
            <UnidadReferencia>62</UnidadReferencia>
        </Item>
    </DetallesItems>
    <Encabezado>
        <Comprador>
            <CodigoInternoComprador>STR</CodigoInternoComprador>
            <ContactoComprador>STR</ContactoComprador>
            <ContactoEntrega>STR</ContactoEntrega>
            <CorreoComprador>STR</CorreoComprador>
            <DireccionComprador>STR</DireccionComprador>
            <DireccionEntrega>STR</DireccionEntrega>
            <FechaEntrega>STR</FechaEntrega>
            <FechaOrdenCompra>STR</FechaOrdenCompra>
            <InformacionAdicionalComprador>STR</InformacionAdicionalComprador>
            <MunicipioComprador>320703</MunicipioComprador>
            <NumeroOrdenCompra>STR</NumeroOrdenCompra>
            <ProvinciaComprador>320703</ProvinciaComprador>
            <RNCComprador>STR</RNCComprador>
            <RazonSocialComprador>STR</RazonSocialComprador>
            <ResponsablePago>STR</ResponsablePago>
            <TelefonoAdicional>STR</TelefonoAdicional>
        </Comprador>
        <Emisor>
            <ActividadEconomica>STR</ActividadEconomica>
            <CodigoVendedor>STR</CodigoVendedor>
            <CorreoEmisor>STR</CorreoEmisor>
            <DireccionEmisor>STR</DireccionEmisor>
            <FechaEmision>STR</FechaEmision>
            <InformacionAdicionalEmisor>STR</InformacionAdicionalEmisor>
            <Municipio>320703</Municipio>
            <NombreComercial>STR</NombreComercial>
            <NumeroFacturaInterna>STR</NumeroFacturaInterna>
            <NumeroPedidoInterno>STR</NumeroPedidoInterno>
            <Provincia>320703</Provincia>
            <RNCEmisor>STR</RNCEmisor>
            <RazonSocialEmisor>STR</RazonSocialEmisor>
            <RutaVenta>STR</RutaVenta>
            <Sucursal>STR</Sucursal>
            <TablaTelefonoEmisor>
                <TelefonoEmisor>STR</TelefonoEmisor>
            </TablaTelefonoEmisor>
            <WebSite>STR</WebSite>
            <ZonaVenta>STR</ZonaVenta>
        </Emisor>
        <IdDoc>
            <BancoPago>STR</BancoPago>
            <FechaDesde>STR</FechaDesde>
            <FechaHasta>STR</FechaHasta>
            <FechaLimitePago>STR</FechaLimitePago>
            <FechaVencimientoSecuencia>STR</FechaVencimientoSecuencia>
            <IndicadorEnvioDiferido>1</IndicadorEnvioDiferido>
            <IndicadorMontoGravado>1</IndicadorMontoGravado>
            <IndicadorServicioTodoIncluido>STR</IndicadorServicioTodoIncluido>
            <NumeroCuentaPago>STR</NumeroCuentaPago>
            <TablaFormasPago>
                <FormaDePago>
                    <FormaPago>8</FormaPago>
                    <MontoPago>STR</MontoPago>
                </FormaDePago>
            </TablaFormasPago>
            <TerminoPago>STR</TerminoPago>
            <TipoCuentaPago>OT</TipoCuentaPago>
            <TipoIngresos>06</TipoIngresos>
            <TipoPago>3</TipoPago>
            <TipoeCF>47</TipoeCF>
            <TotalPaginas>STR</TotalPaginas>
            <eNCF>STR</eNCF>
        </IdDoc>
        <InformacionesAdicionales>
            <CantidadBulto>STR</CantidadBulto>
            <FechaEmbarque>STR</FechaEmbarque>
            <NumeroContenedor>STR</NumeroContenedor>
            <NumeroEmbarque>STR</NumeroEmbarque>
            <NumeroReferencia>STR</NumeroReferencia>
            <PesoBruto>STR</PesoBruto>
            <PesoNeto>STR</PesoNeto>
            <UnidadBulto>62</UnidadBulto>
            <UnidadPesoBruto>62</UnidadPesoBruto>
            <UnidadPesoNeto>62</UnidadPesoNeto>
            <UnidadVolumen>62</UnidadVolumen>
            <VolumenBulto>STR</VolumenBulto>
        </InformacionesAdicionales>
        <OtraMoneda>
            <ImpuestosAdicionalesOtraMoneda>
                <ImpuestoAdicionalOtraMoneda>
                    <MontoImpuestoSelectivoConsumoAdvaloremOtraMoneda>STR</MontoImpuestoSelectivoConsumoAdvaloremOtraMoneda>
                    <MontoImpuestoSelectivoConsumoEspecificoOtraMoneda>STR</MontoImpuestoSelectivoConsumoEspecificoOtraMoneda>
                    <OtrosImpuestosAdicionalesOtraMoneda>STR</OtrosImpuestosAdicionalesOtraMoneda>
                    <TasaImpuestoAdicionalOtraMoneda>STR</TasaImpuestoAdicionalOtraMoneda>
                    <TipoImpuestoOtraMoneda>039</TipoImpuestoOtraMoneda>
                </ImpuestoAdicionalOtraMoneda>
            </ImpuestosAdicionalesOtraMoneda>
            <MontoExentoOtraMoneda>STR</MontoExentoOtraMoneda>
            <MontoGravado1OtraMoneda>STR</MontoGravado1OtraMoneda>
            <MontoGravado2OtraMoneda>STR</MontoGravado2OtraMoneda>
            <MontoGravado3OtraMoneda>STR</MontoGravado3OtraMoneda>
            <MontoGravadoTotalOtraMoneda>STR</MontoGravadoTotalOtraMoneda>
            <MontoImpuestoAdicionalOtraMoneda>STR</MontoImpuestoAdicionalOtraMoneda>
            <MontoTotalOtraMoneda>STR</MontoTotalOtraMoneda>
            <TipoCambio>STR</TipoCambio>
            <TipoMoneda>MXN</TipoMoneda>
            <TotalITBIS1OtraMoneda>STR</TotalITBIS1OtraMoneda>
            <TotalITBIS2OtraMoneda>STR</TotalITBIS2OtraMoneda>
            <TotalITBIS3OtraMoneda>STR</TotalITBIS3OtraMoneda>
            <TotalITBISOtraMoneda>STR</TotalITBISOtraMoneda>
        </OtraMoneda>
        <Totales>
            <ITBIS1>STR</ITBIS1>
            <ITBIS2>STR</ITBIS2>
            <ITBIS3>STR</ITBIS3>
            <ImpuestosAdicionales>
                <ImpuestoAdicional>
                    <MontoImpuestoSelectivoConsumoAdvalorem>STR</MontoImpuestoSelectivoConsumoAdvalorem>
                    <MontoImpuestoSelectivoConsumoEspecifico>STR</MontoImpuestoSelectivoConsumoEspecifico>
                    <OtrosImpuestosAdicionales>STR</OtrosImpuestosAdicionales>
                    <TasaImpuestoAdicional>STR</TasaImpuestoAdicional>
                    <TipoImpuesto>039</TipoImpuesto>
                </ImpuestoAdicional>
            </ImpuestosAdicionales>
            <MontoAvancePago>STR</MontoAvancePago>
            <MontoExento>STR</MontoExento>
            <MontoGravadoI1>STR</MontoGravadoI1>
            <MontoGravadoI2>STR</MontoGravadoI2>
            <MontoGravadoI3>STR</MontoGravadoI3>
            <MontoGravadoTotal>STR</MontoGravadoTotal>
            <MontoImpuestoAdicional>STR</MontoImpuestoAdicional>
            <MontoNoFacturable>STR</MontoNoFacturable>
            <MontoPeriodo>STR</MontoPeriodo>
            <MontoTotal>STR</MontoTotal>
            <SaldoAnterior>STR</SaldoAnterior>
            <TotalISRPercepcion>STR</TotalISRPercepcion>
            <TotalISRRetencion>STR</TotalISRRetencion>
            <TotalITBIS>STR</TotalITBIS>
            <TotalITBIS1>STR</TotalITBIS1>
            <TotalITBIS2>STR</TotalITBIS2>
            <TotalITBIS3>STR</TotalITBIS3>
            <TotalITBISPercepcion>STR</TotalITBISPercepcion>
            <TotalITBISRetenido>STR</TotalITBISRetenido>
            <ValorPagar>STR</ValorPagar>
        </Totales>
        <Transporte>
            <Conductor>STR</Conductor>
            <DocumentoTransporte>STR</DocumentoTransporte>
            <Ficha>STR</Ficha>
            <NumeroAlbaran>STR</NumeroAlbaran>
            <Placa>STR</Placa>
            <RutaTransporte>STR</RutaTransporte>
            <ZonaTransporte>STR</ZonaTransporte>
        </Transporte>
        <Version>1.0</Version>
    </Encabezado>
    <FechaHoraFirma>STR</FechaHoraFirma>
    <InformacionReferencia>
        <CodigoModificacion>5</CodigoModificacion>
        <FechaNCFModificado>STR</FechaNCFModificado>
        <NCFModificado>STR</NCFModificado>
        <RNCOtroContribuyente>STR</RNCOtroContribuyente>
    </InformacionReferencia>
    <Paginacion>
        <Pagina>
            <MontoSubtotalPagina>STR</MontoSubtotalPagina>
            <NoLineaDesde>STR</NoLineaDesde>
            <NoLineaHasta>STR</NoLineaHasta>
            <PaginaNo>STR</PaginaNo>
            <SubtotalExentoPagina>STR</SubtotalExentoPagina>
            <SubtotalImpuestoAdicional>
                <SubtotalImpuestoSelectivoConsumoEspecificoPagina>STR</SubtotalImpuestoSelectivoConsumoEspecificoPagina>
                <SubtotalOtrosImpuesto>STR</SubtotalOtrosImpuesto>
            </SubtotalImpuestoAdicional>
            <SubtotalImpuestoAdicionalPagina>STR</SubtotalImpuestoAdicionalPagina>
            <SubtotalItbis1Pagina>STR</SubtotalItbis1Pagina>
            <SubtotalItbis2Pagina>STR</SubtotalItbis2Pagina>
            <SubtotalItbis3Pagina>STR</SubtotalItbis3Pagina>
            <SubtotalItbisPagina>STR</SubtotalItbisPagina>
            <SubtotalMontoGravado1Pagina>STR</SubtotalMontoGravado1Pagina>
            <SubtotalMontoGravado2Pagina>STR</SubtotalMontoGravado2Pagina>
            <SubtotalMontoGravado3Pagina>STR</SubtotalMontoGravado3Pagina>
            <SubtotalMontoGravadoPagina>STR</SubtotalMontoGravadoPagina>
            <SubtotalMontoNoFacturablePagina>STR</SubtotalMontoNoFacturablePagina>
        </Pagina>
    </Paginacion>
    <Subtotales>
        <Subtotal>
            <DescripcionSubtotal>STR</DescripcionSubtotal>
            <Lineas>STR</Lineas>
            <MontoSubTotal>STR</MontoSubTotal>
            <NumeroSubTotal>STR</NumeroSubTotal>
            <Orden>STR</Orden>
            <SubTotaITBIS>STR</SubTotaITBIS>
            <SubTotaITBIS1>STR</SubTotaITBIS1>
            <SubTotaITBIS2>STR</SubTotaITBIS2>
            <SubTotaITBIS3>STR</SubTotaITBIS3>
            <SubTotalExento>STR</SubTotalExento>
            <SubTotalImpuestoAdicional>STR</SubTotalImpuestoAdicional>
            <SubTotalMontoGravadoI1>STR</SubTotalMontoGravadoI1>
            <SubTotalMontoGravadoI2>STR</SubTotalMontoGravadoI2>
            <SubTotalMontoGravadoI3>STR</SubTotalMontoGravadoI3>
            <SubTotalMontoGravadoTotal>STR</SubTotalMontoGravadoTotal>
        </Subtotal>
    </Subtotales>
</ECF>
